repo: ajay-ghibli-frontend
name: ghibliuniverse-frontend
namespace: fma
image: docker.myob.com/future-makers-academy/ajay-ghibli-frontend
containerPort: "80"
host: ghibliuniverse-frontend.svc.platform.myobdev.com
